<?php
/**
 * MustrHQ — web installer (run once, then delete this file).
 *
 * This is a standalone setup wizard. It does not depend on the app's own
 * config/helpers, because those assume config.php is already filled in.
 * Steps: requirements  ->  details (DB + site + admin)  ->  done.
 */

define('ROOT', __DIR__);
define('CONFIG_FILE', ROOT . '/config.php');
define('SCHEMA_FILE', ROOT . '/schema.sql');
define('UPLOADS_DIR', ROOT . '/uploads');

if (is_file(CONFIG_FILE)) {
    require CONFIG_FILE; // defines DB_* etc. (placeholder values on a fresh copy)
}

session_name('kclock_install');
session_start();
if (empty($_SESSION['itoken'])) {
    $_SESSION['itoken'] = bin2hex(random_bytes(16));
}

/* ----------------------------- small helpers ----------------------------- */

function esc($s): string { return htmlspecialchars((string) $s, ENT_QUOTES, 'UTF-8'); }
function itoken(): string { return $_SESSION['itoken']; }
function icheck(): void
{
    if (!hash_equals($_SESSION['itoken'] ?? '', $_POST['itoken'] ?? '')) {
        http_response_code(400);
        exit('Your setup session expired. Reload install.php and start again.');
    }
}

function installer_pdo(string $host, string $name, string $user, string $pass): PDO
{
    $dsn = 'mysql:host=' . $host . ';dbname=' . $name . ';charset=utf8mb4';
    return new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
}

function build_config(array $v): string
{
    $q = function ($x) { return "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], (string) $x) . "'"; };
    return "<?php\n"
        . "/**\n * MustrHQ — configuration (generated by install.php)\n * You can edit these values by hand at any time.\n */\n\n"
        . "// ---- Database ----\n"
        . "define('DB_HOST', " . $q($v['db_host']) . ");\n"
        . "define('DB_NAME', " . $q($v['db_name']) . ");\n"
        . "define('DB_USER', " . $q($v['db_user']) . ");\n"
        . "define('DB_PASS', " . $q($v['db_pass']) . ");\n\n"
        . "// ---- App settings ----\n"
        . "define('APP_NAME', " . $q($v['app_name']) . ");\n"
        . "define('APP_TZ', " . $q($v['app_tz']) . ");\n"
        . "define('CURRENCY', " . $q($v['currency']) . ");\n\n"
        . "// ---- Attendance rules ----\n"
        . "define('GRACE_MINUTES', 10);        // minutes after expected start before a clock-in is \"late\"\n"
        . "define('NOSHOW_AFTER_MINUTES', 60); // minutes past expected start with no clock-in => \"no-show\"\n\n"
        . "// ---- Kiosk PIN safety ----\n"
        . "define('PIN_MAX_ATTEMPTS', 5);\n"
        . "define('PIN_LOCK_SECONDS', 60);\n\n"
        . "// ---- Kiosk gate (empty = open; a value locks the kiosk to devices that visited with ?key=) ----\n"
        . "define('KIOSK_KEY', " . $q($v['kiosk_key']) . ");\n\n"
        . "// ---- Session cookie name ----\n"
        . "define('SESSION_NAME', 'kclock');\n\n"
        . "define('INSTALLED', true);\n";
}

function run_schema(PDO $pdo): void
{
    $sql = file_get_contents(SCHEMA_FILE);
    if ($sql === false) throw new RuntimeException('Could not read schema.sql — make sure it was uploaded.');

    // Strip comments BEFORE splitting on ';', otherwise a ';' inside a comment
    // (e.g. "-- UTC; NULL = ...") would chop a statement in half.
    // This schema has no ';', '--' or '#' inside string literals, so a plain
    // strip is safe here.
    $sql = preg_replace('#/\*.*?\*/#s', '', $sql);   // /* block */ comments
    $sql = preg_replace('/--[^\r\n]*/', '', $sql);   // -- line comments (anywhere on the line)
    $sql = preg_replace('/#[^\r\n]*/', '', $sql);    // # line comments

    $statements = array_filter(array_map('trim', explode(';', $sql)), function ($s) { return $s !== ''; });
    foreach ($statements as $st) {
        // don't duplicate the starter brands/roles if they already exist
        if (preg_match('/^INSERT\s+INTO\s+brands\b/i', $st)) {
            if ((int) $pdo->query('SELECT COUNT(*) FROM brands')->fetchColumn() > 0) continue;
        } elseif (preg_match('/^INSERT\s+INTO\s+roles\b/i', $st)) {
            if ((int) $pdo->query('SELECT COUNT(*) FROM roles')->fetchColumn() > 0) continue;
        }
        $pdo->exec($st);
    }
}

function create_admin(PDO $pdo, string $user, string $passHash): void
{
    if ((int) $pdo->query('SELECT COUNT(*) FROM admins')->fetchColumn() === 0) {
        $pdo->prepare('INSERT INTO admins (username, password_hash, created_at) VALUES (?,?,?)')
            ->execute([$user, $passHash, gmdate('Y-m-d H:i:s')]);
    }
}

function ensure_htaccess(): void
{
    if (!is_dir(UPLOADS_DIR)) @mkdir(UPLOADS_DIR, 0755, true);
    $h = UPLOADS_DIR . '/.htaccess';
    if (is_dir(UPLOADS_DIR) && !is_file($h)) {
        @file_put_contents($h, "<FilesMatch \"\\.(php|php3|php4|php5|php7|phtml|pht|phar|cgi|pl|py|asp|aspx|sh)$\">\n    Require all denied\n</FilesMatch>\nOptions -ExecCGI -Indexes\n");
    }

    // No directory listings anywhere, and keep sensitive files unreachable.
    $root = __DIR__ . '/.htaccess';
    if (!is_file($root)) {
        @file_put_contents($root,
            "Options -Indexes\n"
            . "DirectoryIndex index.php index.html\n\n"
            . "<FilesMatch \"(^\\.|\\.(sql|zip|tar|gz|md|log|bak|old|ini|sh)$)\">\n"
            . "    Require all denied\n"
            . "    <IfModule !mod_authz_core.c>\n        Order allow,deny\n        Deny from all\n    </IfModule>\n"
            . "</FilesMatch>\n\n"
            . "<Files \"config.php\">\n    Require all denied\n"
            . "    <IfModule !mod_authz_core.c>\n        Order allow,deny\n        Deny from all\n    </IfModule>\n</Files>\n");
    }

    // Backups may contain source code — never serve them.
    $bdir = __DIR__ . '/backups';
    if (!is_dir($bdir)) @mkdir($bdir, 0755, true);
    $bh = $bdir . '/.htaccess';
    if (is_dir($bdir) && !is_file($bh)) {
        @file_put_contents($bh, "Require all denied\n<IfModule !mod_authz_core.c>\n    Order allow,deny\n    Deny from all\n</IfModule>\n");
    }
}

/* ------------------------------- rendering ------------------------------- */

function head(string $title, int $active): void
{
    $steps = [1 => 'Requirements', 2 => 'Details', 3 => 'Done'];
    echo '<!doctype html><html lang="en"><head><meta charset="utf-8">';
    echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
    echo '<title>' . esc($title) . ' · MustrHQ setup</title>';
    echo '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
    echo '<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">';
    $cssV = @filemtime(__DIR__ . '/assets/style.css');
    echo '<link rel="stylesheet" href="assets/style.css' . ($cssV ? '?v=' . $cssV : '') . '">';
    echo '<style>
      .install-wrap{max-width:660px;margin:36px auto;padding:0 20px}
      .install-head{margin-bottom:14px}
      .stepline{display:flex;gap:8px;margin:0 0 22px;font-size:13px}
      .stepline span{padding:5px 12px;border:1px solid var(--line);border-radius:20px;background:#fff;color:var(--muted)}
      .stepline span.on{background:var(--accent);color:#fff;border-color:var(--accent)}
      .stepline span.done{color:var(--accent-deep);border-color:var(--accent)}
      .reqs{width:100%;border-collapse:collapse;margin:2px 0}
      .reqs td{padding:10px 8px;border-bottom:1px solid var(--line);vertical-align:top}
      .reqs td.s{text-align:right;white-space:nowrap;font-weight:600}
      .ok{color:var(--accent-deep)} .warn{color:var(--warn)} .bad{color:var(--danger)}
      .sec-title{font-family:var(--font-display);font-weight:600;font-size:16px;margin:22px 0 12px;padding-top:14px;border-top:1px solid var(--line)}
      .sec-title:first-of-type{border-top:none;padding-top:0;margin-top:6px}
      pre.cfg{white-space:pre;overflow:auto;padding:14px;background:#0f1216;color:#e7ecf1;border-radius:10px;font-family:var(--font-mono);font-size:12.5px;line-height:1.55}
      .note{font-size:13px;color:var(--muted)}
    </style>';
    echo '</head><body class="admin"><div class="install-wrap">';
    echo '<div class="install-head"><div class="brand big">MustrHQ <span class="brand-sub">setup</span></div></div>';
    echo '<div class="stepline">';
    foreach ($steps as $n => $label) {
        $cls = $n === $active ? 'on' : ($n < $active ? 'done' : '');
        echo '<span class="' . $cls . '">' . $n . '. ' . esc($label) . '</span>';
    }
    echo '</div>';
}

function foot(): void { echo '</div></body></html>'; }

function render_locked(): void
{
    head('Already installed', 3);
    echo '<div class="card"><h1>MustrHQ is already installed</h1>';
    echo '<p class="note">The database is set up and an admin account exists. For safety, delete <code>install.php</code> (and <code>admin/setup.php</code>) from your server.</p>';
    echo '<div class="actions" style="margin-top:14px"><a class="btn" href="admin/login.php">Go to admin</a> <a class="btn ghost" href="kiosk/index.php">Open kiosk</a></div></div>';
    foot();
}

function render_welcome(array $reqs, bool $hardFail): void
{
    head('Requirements', 1);
    echo '<div class="card">';
    echo '<h1>Welcome</h1>';
    echo '<p class="note">This installer will set up the database and create your manager login. Before you start, create a MySQL database and user in cPanel (MySQL® Databases) — the installer fills in the rest.</p>';
    echo '<div class="flash warn" style="margin-top:14px">Run this now and <strong>delete install.php afterwards</strong>. While it exists on a fresh, unconfigured copy, anyone who can reach this page could complete setup in your place.</div>';
    echo '<h2 style="font-family:var(--font-display);font-size:16px;margin:20px 0 8px">Server checks</h2>';
    echo '<table class="reqs"><tbody>';
    foreach ($reqs as $r) {
        $badge = $r['ok'] ? '<span class="ok">OK</span>' : ($r['hard'] ? '<span class="bad">Required</span>' : '<span class="warn">Optional</span>');
        echo '<tr><td>' . esc($r['label']) . ($r['detail'] ? '<div class="note">' . esc($r['detail']) . '</div>' : '') . '</td><td class="s">' . $badge . '</td></tr>';
    }
    echo '</tbody></table>';
    if ($hardFail) {
        echo '<div class="flash err" style="margin-top:14px">Some required items are missing. Fix them (or ask your host), then reload this page.</div>';
        echo '<div class="actions" style="margin-top:6px"><a class="btn ghost" href="install.php">Re-check</a></div>';
    } else {
        echo '<div class="actions" style="margin-top:16px"><a class="btn" href="install.php?step=config">Start setup</a></div>';
    }
    echo '</div>';
    foot();
}

function render_form(array $v, array $errors): void
{
    head('Details', 2);
    echo '<div class="card">';
    if ($errors) {
        echo '<div class="flash err">' . implode('<br>', array_map('esc', $errors)) . '</div>';
    }
    echo '<form method="post" action="install.php" autocomplete="off">';
    echo '<input type="hidden" name="step" value="run"><input type="hidden" name="itoken" value="' . esc(itoken()) . '">';

    echo '<div class="sec-title">Database</div>';
    echo '<div class="form-grid">';
    echo '<label>Host<input type="text" name="db_host" value="' . esc($v['db_host']) . '" required></label>';
    echo '<label>Database name<input type="text" name="db_name" value="' . esc($v['db_name']) . '" required></label>';
    echo '<label>Database user<input type="text" name="db_user" value="' . esc($v['db_user']) . '" required></label>';
    echo '<label>Database password<input type="password" name="db_pass" value="' . esc($v['db_pass']) . '"></label>';
    echo '</div><div class="note">On cPanel the host is usually <code>localhost</code>, and names/users are prefixed with your account name.</div>';

    echo '<div class="sec-title">Site</div>';
    echo '<div class="form-grid">';
    echo '<label>App name<input type="text" name="app_name" value="' . esc($v['app_name']) . '" required maxlength="100"></label>';
    echo '<label>Currency symbol<input type="text" name="currency" value="' . esc($v['currency']) . '" required maxlength="8"></label>';
    echo '</div>';
    echo '<label>Timezone<select name="app_tz">';
    foreach (DateTimeZone::listIdentifiers() as $tz) {
        echo '<option value="' . esc($tz) . '"' . ($tz === $v['app_tz'] ? ' selected' : '') . '>' . esc($tz) . '</option>';
    }
    echo '</select></label>';
    echo '<label class="note" style="display:flex;align-items:center;gap:8px;margin-top:4px"><input type="checkbox" name="kiosk_lock" value="1" style="width:auto"' . (!empty($v['kiosk_lock']) ? ' checked' : '') . '> Lock the kiosk to specific devices (recommended) — generates a key you visit once on the tablet</label>';

    echo '<div class="sec-title">Admin account</div>';
    echo '<div class="form-grid">';
    echo '<label>Username<input type="text" name="admin_user" value="' . esc($v['admin_user']) . '" required maxlength="60"></label>';
    echo '<label>Password<input type="password" name="admin_pass" required minlength="8"></label>';
    echo '</div>';
    echo '<label>Confirm password<input type="password" name="admin_pass2" required minlength="8"></label>';

    echo '<div class="actions" style="margin-top:16px"><button class="btn" type="submit">Install</button></div>';
    echo '</form></div>';
    foot();
}

function render_manual_config(array $v, string $content): void
{
    head('Details', 2);
    echo '<div class="card">';
    echo '<div class="flash warn">The installer could not write <code>config.php</code> automatically (the folder isn\'t writable). Create the file yourself, then continue.</div>';
    echo '<ol class="note" style="margin:0 0 12px 18px"><li>Create/replace <code>config.php</code> in the app folder with exactly the contents below.</li><li>Then click Continue — the installer will build the database and admin account.</li></ol>';
    echo '<pre class="cfg">' . esc($content) . '</pre>';
    echo '<form method="post" action="install.php">';
    echo '<input type="hidden" name="step" value="run"><input type="hidden" name="itoken" value="' . esc(itoken()) . '">';
    echo '<input type="hidden" name="config_written" value="1">';
    foreach (['db_host','db_name','db_user','db_pass','app_name','currency','app_tz','admin_user','admin_pass','kiosk_key'] as $k) {
        echo '<input type="hidden" name="' . $k . '" value="' . esc($v[$k] ?? '') . '">';
    }
    if (!empty($v['kiosk_lock'])) echo '<input type="hidden" name="kiosk_lock" value="1">';
    echo '<input type="hidden" name="admin_pass2" value="' . esc($v['admin_pass'] ?? '') . '">';
    echo '<div class="actions" style="margin-top:14px"><button class="btn" type="submit">I\'ve created config.php — continue</button></div>';
    echo '</form></div>';
    foot();
}

function render_done(): void
{
    $key = $_SESSION['done_kiosk_key'] ?? '';
    head('Done', 3);
    echo '<div class="card">';
    echo '<h1>Setup complete</h1>';
    echo '<p class="note">Your database is ready and the admin account is created.</p>';
    echo '<div class="flash err" style="margin-top:12px"><strong>Delete install.php now</strong> (and <code>admin/setup.php</code>) so nobody can run setup again.</div>';
    if ($key !== '') {
        echo '<div class="sec-title">Kiosk key</div>';
        echo '<p class="note">On the tablet only, open this address once to unlock the kiosk on that device:</p>';
        echo '<pre class="cfg">kiosk/index.php?key=' . esc($key) . '</pre>';
        echo '<p class="note">Keep this key private. It is stored in your config.php.</p>';
    }
    echo '<div class="actions" style="margin-top:16px"><a class="btn" href="admin/login.php">Log in to admin</a> <a class="btn ghost" href="kiosk/index.php">Open kiosk</a></div>';
    echo '</div>';
    foot();
}

/* -------------------------------- routing -------------------------------- */

$step = $_POST['step'] ?? $_GET['step'] ?? 'welcome';

// success page first, so the post-install redirect always lands here
if ($step === 'done') {
    if (empty($_SESSION['install_complete'])) { header('Location: install.php'); exit; }
    render_done();
    exit;
}

// already installed? (real DB in config + an admin row)
$alreadyInstalled = false;
if (defined('DB_NAME') && DB_NAME !== 'your_db_name') {
    try {
        $probe = installer_pdo(DB_HOST, DB_NAME, DB_USER, DB_PASS);
        if ((int) $probe->query('SELECT COUNT(*) FROM admins')->fetchColumn() > 0) {
            $alreadyInstalled = true;
        }
    } catch (Throwable $e) { /* not actually installed */ }
}
if ($alreadyInstalled) { render_locked(); exit; }

if ($step === 'run' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    icheck();

    $v = [
        'db_host'   => trim($_POST['db_host'] ?? ''),
        'db_name'   => trim($_POST['db_name'] ?? ''),
        'db_user'   => trim($_POST['db_user'] ?? ''),
        'db_pass'   => (string) ($_POST['db_pass'] ?? ''),
        'app_name'  => trim($_POST['app_name'] ?? 'MustrHQ'),
        'app_tz'    => trim($_POST['app_tz'] ?? 'Europe/London'),
        'currency'  => trim($_POST['currency'] ?? '£'),
        'admin_user' => trim($_POST['admin_user'] ?? ''),
        'admin_pass' => (string) ($_POST['admin_pass'] ?? ''),
        'admin_pass2' => (string) ($_POST['admin_pass2'] ?? ''),
        'kiosk_lock' => !empty($_POST['kiosk_lock']) ? '1' : '',
    ];
    // keep a previously generated kiosk key across the manual-config round trip
    if (isset($_POST['kiosk_key']) && $_POST['kiosk_key'] !== '') {
        $v['kiosk_key'] = (string) $_POST['kiosk_key'];
    } else {
        $v['kiosk_key'] = $v['kiosk_lock'] ? bin2hex(random_bytes(16)) : '';
    }

    $errors = [];
    if ($v['db_host'] === '' || $v['db_name'] === '' || $v['db_user'] === '') $errors[] = 'Fill in the database host, name and user.';
    if ($v['app_name'] === '') $errors[] = 'Enter an app name.';
    if ($v['currency'] === '') $errors[] = 'Enter a currency symbol.';
    if (!in_array($v['app_tz'], DateTimeZone::listIdentifiers(), true)) $errors[] = 'Choose a valid timezone.';
    if ($v['admin_user'] === '' || mb_strlen($v['admin_user']) > 60) $errors[] = 'Enter an admin username (up to 60 characters).';
    if (strlen($v['admin_pass']) < 8) $errors[] = 'Use an admin password of at least 8 characters.';
    if ($v['admin_pass'] !== $v['admin_pass2']) $errors[] = 'The admin passwords do not match.';

    $pdo = null;
    if (!$errors) {
        try {
            $pdo = installer_pdo($v['db_host'], $v['db_name'], $v['db_user'], $v['db_pass']);
        } catch (Throwable $e) {
            $errors[] = 'Could not connect to the database: ' . $e->getMessage();
            $errors[] = 'Check the details, and make sure the database exists and the user has access to it (both are created in cPanel → MySQL Databases).';
        }
    }
    if ($errors) { render_form($v, $errors); exit; }

    // write config.php (or fall back to manual creation)
    if (empty($_POST['config_written'])) {
        $written = @file_put_contents(CONFIG_FILE, build_config($v), LOCK_EX);
        if ($written === false) { render_manual_config($v, build_config($v)); exit; }
    }

    try {
        run_schema($pdo);
        create_admin($pdo, $v['admin_user'], password_hash($v['admin_pass'], PASSWORD_DEFAULT));
        ensure_htaccess();
    } catch (Throwable $e) {
        render_form($v, ['The database step failed: ' . $e->getMessage()]);
        exit;
    }

    $_SESSION['done_kiosk_key'] = $v['kiosk_key'];
    $_SESSION['install_complete'] = true;
    header('Location: install.php?step=done');
    exit;
}

if ($step === 'config') {
    render_form([
        'db_host' => 'localhost', 'db_name' => '', 'db_user' => '', 'db_pass' => '',
        'app_name' => 'MustrHQ', 'app_tz' => 'Europe/London', 'currency' => '£',
        'admin_user' => '', 'admin_pass' => '', 'admin_pass2' => '', 'kiosk_lock' => '', 'kiosk_key' => '',
    ], []);
    exit;
}

/* default: requirements */
$reqs = [
    ['label' => 'PHP 7.4 or newer', 'ok' => version_compare(PHP_VERSION, '7.4.0', '>='), 'hard' => true, 'detail' => 'You have PHP ' . PHP_VERSION],
    ['label' => 'MySQL support (pdo_mysql)', 'ok' => extension_loaded('pdo_mysql'), 'hard' => true, 'detail' => ''],
    ['label' => 'Multibyte strings (mbstring)', 'ok' => extension_loaded('mbstring'), 'hard' => true, 'detail' => ''],
    ['label' => 'JSON support', 'ok' => function_exists('json_encode'), 'hard' => true, 'detail' => ''],
    ['label' => 'Image detection (fileinfo)', 'ok' => extension_loaded('fileinfo'), 'hard' => false, 'detail' => 'Needed only for staff photo uploads'],
    ['label' => 'config.php is writable', 'ok' => is_file(CONFIG_FILE) && is_writable(CONFIG_FILE), 'hard' => false, 'detail' => "If not, you'll be shown the file to create by hand"],
    ['label' => 'uploads/ is writable', 'ok' => is_dir(UPLOADS_DIR) && is_writable(UPLOADS_DIR), 'hard' => false, 'detail' => 'Needed only for staff photo uploads'],
];
$hardFail = false;
foreach ($reqs as $r) { if ($r['hard'] && !$r['ok']) $hardFail = true; }
render_welcome($reqs, $hardFail);
